errorTestHome:
    pattern:  /index
    defaults: { _controller: errorHandling.testController:indexAction }
    requirements: { _method: GET }

errorTestNotice:
    pattern:  /notice
    defaults: { _controller: errorHandling.testController:noticeAction }
    requirements: { _method: GET|POST }

errorTestWarning:
    pattern:  /warning
    defaults: { _controller: errorHandling.testController:warningAction }
    requirements: { _method: GET|POST }

errorTestException:
    pattern:  /exception
    defaults: { _controller: errorHandling.testController:exceptionAction }
    requirements: { _method: GET|POST }

errorTestFatal:
    pattern:  /fatal
    defaults: { _controller: errorHandling.testController:fatalAction }
    requirements: { _method: GET|POST }

errorTestError:
    pattern:  /error
    defaults: { _controller: errorHandling.testController:errorAction }
    requirements: { _method: GET|POST }